name: Deploy Something

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        stage: ['dev']
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      stage: ${{ matrix.stage }}​
