name: 'Resuable Deploy Serverless'

on:
  workflow_call:
    inputs:
      stage:
        description: 'The serverless deployment stage to use.'
        type: string
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
          cache: yarn

      - name: Install project dependencies
        run: yarn install --frozen-lockfile

      - name: inspect inputs.stage
        run: echo '${{ inputs.stage }}'

      - name: debug step
        run: yarn serverless print --stage `${STAGE}`
        env:
          STAGE: ${{ inputs.stage }}
